// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Praieiro profile (sovereign identity) and roles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const { data: profile, error } = await supabase.from("profiles").select("id, full_name, email, user_type, created_at").eq("id", uid).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!profile) {
      return { content: [{ type: "text", text: "Perfil n\xE3o encontrado. Complete o perfil no app." }], isError: true };
    }
    const { data: roles } = await supabase.from("user_roles").select("role").eq("user_id", uid);
    const payload = { profile, roles: (roles ?? []).map((r) => r.role) };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-vendors.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_vendors_default = defineTool2({
  name: "list_vendors",
  title: "List ambulantes (vendors)",
  description: "List Praieiro ambulantes (beach vendors) with their category, establishment type and status.",
  inputSchema: {
    category: z.string().trim().optional().describe("Filter by product category (partial match)."),
    limit: z.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("vendors").select("profile_id, product_category, product_description, establishment_type, status, updated_at").order("updated_at", { ascending: false }).limit(take);
    if (category) query = query.ilike("product_category", `%${category}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { vendors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_products_default = defineTool3({
  name: "list_products",
  title: "List products",
  description: "List products in the Praieiro marketplace, optionally filtered by vendor.",
  inputSchema: {
    vendorId: z2.string().uuid().optional().describe("Vendor profile id to filter by."),
    availableOnly: z2.boolean().optional().describe("Only products currently available."),
    limit: z2.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ vendorId, availableOnly, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("id, vendor_id, name, description, price, is_available, created_at").order("created_at", { ascending: false }).limit(take);
    if (vendorId) query = query.eq("vendor_id", vendorId);
    if (availableOnly) query = query.eq("is_available", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in user's Praieiro orders (as client or as vendor), newest first.",
  inputSchema: {
    status: z3.string().trim().optional().describe("Filter by order status."),
    limit: z3.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select(
      "id, client_id, vendor_id, status, payment_status, total_amount, message, created_at, proximity_verified"
    ).order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-zimbu-balance.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var get_my_zimbu_balance_default = defineTool5({
  name: "get_my_zimbu_balance",
  title: "Get my ZIMBU balance",
  description: "Compute the signed-in user's ZIMBU balance dynamically from the append-only Satoshi ledger (no stored balances) and return the latest ledger entries.",
  inputSchema: {
    entries: z4.number().int().optional().describe("How many recent ledger entries to include (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ entries }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(entries ?? 10, 1), 50);
    const supabase = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const { data, error } = await supabase.from("ledger").select("id, entry_type, currency, amount, description, status, created_at, satoshi_hash").eq("profile_id", uid).order("created_at", { ascending: false }).limit(500);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const balance = rows.filter((r) => r.status !== "reverted" && r.status !== "cancelled").reduce((sum, r) => {
      const amount = Number(r.amount) || 0;
      const type = String(r.entry_type ?? "").toLowerCase();
      const signed = type.includes("debit") || type.includes("withdraw") || type.includes("saida") ? -amount : amount;
      return sum + signed;
    }, 0);
    const payload = {
      balance,
      currency: "ZIMBU",
      ledgerEntryCount: rows.length,
      recentEntries: rows.slice(0, take)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "egrjizrbwighobujjaaf";
var mcp_default = defineMcp({
  name: "remix-of-praieiro-connect",
  title: "Remix of Praieiro Connect",
  version: "0.1.0",
  instructions: "Ferramentas do ecossistema Praieiro (marketplace de ambulantes de praia). Use get_my_profile para identidade e pap\xE9is, list_vendors e list_products para descoberta, list_my_orders para pedidos do usu\xE1rio autenticado e get_my_zimbu_balance para o saldo ZIMBU calculado dinamicamente a partir do ledger append-only (nenhum saldo \xE9 armazenado).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_vendors_default, list_products_default, list_my_orders_default, get_my_zimbu_balance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
